### ISSUE TITLE
TODO: 

### ISSUE THREAD

**Issue by mukitmomin** [aws-solutions/generative-ai-application-builder-on-aws#83]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.0.0]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "(SO0276) - Generative AI Application Builder on AWS Solution. Version v1.0.0".

- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by ihmaws** [comment]
Thanks for the issue, we will have a look!

**Comment by ihmaws** [comment]
Resolved as of [v1.3.3](https://github.com/aws-solutions/generative-ai-application-builder-on-aws/releases/tag/v1.3.3)
